# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from CityGML2IFC import Transform_generator,import_ifc_data,save_ifc_data
import os
import time

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(903, 397)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_general.sizePolicy().hasHeightForWidth())
        self.tab_general.setSizePolicy(sizePolicy)
        self.tab_general.setObjectName("tab_general")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_general)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line_import_path = QtWidgets.QLineEdit(self.tab_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_import_path.sizePolicy().hasHeightForWidth())
        self.line_import_path.setSizePolicy(sizePolicy)
        self.line_import_path.setMinimumSize(QtCore.QSize(400, 25))
        self.line_import_path.setObjectName("line_import_path")
        self.gridLayout_4.addWidget(self.line_import_path, 0, 2, 1, 1)
        self.line_save_path = QtWidgets.QLineEdit(self.tab_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_save_path.sizePolicy().hasHeightForWidth())
        self.line_save_path.setSizePolicy(sizePolicy)
        self.line_save_path.setMinimumSize(QtCore.QSize(400, 25))
        self.line_save_path.setObjectName("line_save_path")
        self.gridLayout_4.addWidget(self.line_save_path, 1, 2, 1, 1)
        self.button_start = QtWidgets.QPushButton(self.tab_general)
        self.button_start.setObjectName("button_start")
        self.gridLayout_4.addWidget(self.button_start, 6, 0, 1, 2)
        self.button_save = QtWidgets.QPushButton(self.tab_general)
        self.button_save.setObjectName("button_save")
        self.gridLayout_4.addWidget(self.button_save, 1, 0, 1, 2)
        self.button_import = QtWidgets.QPushButton(self.tab_general)
        self.button_import.setObjectName("button_import")
        self.gridLayout_4.addWidget(self.button_import, 0, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.tab_general)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.check_reference_point = QtWidgets.QCheckBox(self.frame_2)
        self.check_reference_point.setChecked(True)
        self.check_reference_point.setObjectName("check_reference_point")
        self.verticalLayout.addWidget(self.check_reference_point)
        self.check_address = QtWidgets.QCheckBox(self.frame_2)
        self.check_address.setChecked(True)
        self.check_address.setObjectName("check_address")
        self.verticalLayout.addWidget(self.check_address)
        self.gridLayout_4.addWidget(self.frame_2, 0, 3, 2, 1)
        self.progressBar = QtWidgets.QProgressBar(self.tab_general)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 7, 0, 1, 4)
        self.frame_3 = QtWidgets.QFrame(self.tab_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.line_input_x = QtWidgets.QLineEdit(self.frame_3)
        self.line_input_x.setObjectName("line_input_x")
        self.gridLayout.addWidget(self.line_input_x, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.line_input_y = QtWidgets.QLineEdit(self.frame_3)
        self.line_input_y.setObjectName("line_input_y")
        self.gridLayout.addWidget(self.line_input_y, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.line_input_z = QtWidgets.QLineEdit(self.frame_3)
        self.line_input_z.setObjectName("line_input_z")
        self.gridLayout.addWidget(self.line_input_z, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 5, 0, 1, 4)
        self.frame = QtWidgets.QFrame(self.tab_general)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.line_input_epsg = QtWidgets.QLineEdit(self.frame)
        self.line_input_epsg.setObjectName("line_input_epsg")
        self.gridLayout_5.addWidget(self.line_input_epsg, 1, 1, 1, 1)
        self.line_output_epsg = QtWidgets.QLineEdit(self.frame)
        self.line_output_epsg.setObjectName("line_output_epsg")
        self.gridLayout_5.addWidget(self.line_output_epsg, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 4, 0, 1, 4)
        self.status = QtWidgets.QLabel(self.tab_general)
        self.status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status.setObjectName("status")
        self.gridLayout_4.addWidget(self.status, 6, 3, 1, 1)
        self.tabWidget.addTab(self.tab_general, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_site_description = QtWidgets.QLineEdit(self.tab_2)
        self.line_site_description.setText("")
        self.line_site_description.setObjectName("line_site_description")
        self.gridLayout_2.addWidget(self.line_site_description, 15, 2, 1, 1)
        self.line_project_descirption = QtWidgets.QPlainTextEdit(self.tab_2)
        self.line_project_descirption.setPlainText("")
        self.line_project_descirption.setObjectName("line_project_descirption")
        self.gridLayout_2.addWidget(self.line_project_descirption, 11, 2, 3, 1)
        self.line_given_name = QtWidgets.QLineEdit(self.tab_2)
        self.line_given_name.setText("")
        self.line_given_name.setObjectName("line_given_name")
        self.gridLayout_2.addWidget(self.line_given_name, 6, 2, 1, 1)
        self.line_project_long_name = QtWidgets.QLineEdit(self.tab_2)
        self.line_project_long_name.setText("")
        self.line_project_long_name.setObjectName("line_project_long_name")
        self.gridLayout_2.addWidget(self.line_project_long_name, 12, 0, 1, 1)
        self.line_organization_name = QtWidgets.QLineEdit(self.tab_2)
        self.line_organization_name.setInputMask("")
        self.line_organization_name.setText("")
        self.line_organization_name.setFrame(True)
        self.line_organization_name.setObjectName("line_organization_name")
        self.gridLayout_2.addWidget(self.line_organization_name, 4, 0, 1, 1)
        self.line_organization_description = QtWidgets.QLineEdit(self.tab_2)
        self.line_organization_description.setText("")
        self.line_organization_description.setObjectName("line_organization_description")
        self.gridLayout_2.addWidget(self.line_organization_description, 4, 2, 1, 1)
        self.line_project_phase = QtWidgets.QLineEdit(self.tab_2)
        self.line_project_phase.setText("")
        self.line_project_phase.setObjectName("line_project_phase")
        self.gridLayout_2.addWidget(self.line_project_phase, 13, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 14, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 10, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 5, 0, 1, 1)
        self.line_project_name = QtWidgets.QLineEdit(self.tab_2)
        self.line_project_name.setText("")
        self.line_project_name.setObjectName("line_project_name")
        self.gridLayout_2.addWidget(self.line_project_name, 11, 0, 1, 1)
        self.line_site_name = QtWidgets.QLineEdit(self.tab_2)
        self.line_site_name.setText("")
        self.line_site_name.setObjectName("line_site_name")
        self.gridLayout_2.addWidget(self.line_site_name, 15, 0, 1, 1)
        self.line_family_name = QtWidgets.QLineEdit(self.tab_2)
        self.line_family_name.setText("")
        self.line_family_name.setObjectName("line_family_name")
        self.gridLayout_2.addWidget(self.line_family_name, 6, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_import_info = QtWidgets.QPushButton(self.frame_4)
        self.button_import_info.setObjectName("button_import_info")
        self.horizontalLayout.addWidget(self.button_import_info)
        self.button_save_info = QtWidgets.QPushButton(self.frame_4)
        self.button_save_info.setObjectName("button_save_info")
        self.horizontalLayout.addWidget(self.button_save_info)
        self.gridLayout_2.addWidget(self.frame_4, 3, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 2, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionAdd_Project_Information = QtGui.QAction(MainWindow)
        self.actionAdd_Project_Information.setObjectName("actionAdd_Project_Information")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CityGML2IFC"))
        self.button_start.setText(_translate("MainWindow", "Start"))
        self.button_save.setText(_translate("MainWindow", "Save As"))
        self.button_import.setText(_translate("MainWindow", "Import GML"))
        self.check_reference_point.setText(_translate("MainWindow", "move by Reference Point"))
        self.check_address.setText(_translate("MainWindow", "import Address"))
        self.line_input_x.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "X"))
        self.line_input_y.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Z"))
        self.line_input_z.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Y"))
        self.label_3.setText(_translate("MainWindow", "Reference Point"))
        self.line_input_epsg.setText(_translate("MainWindow", "25832"))
        self.line_output_epsg.setText(_translate("MainWindow", "5683"))
        self.label_8.setText(_translate("MainWindow", "Output Code"))
        self.label_7.setText(_translate("MainWindow", "Input Code"))
        self.label_2.setText(_translate("MainWindow", "EPSG Code"))
        self.status.setText(_translate("MainWindow", " "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_general), _translate("MainWindow", "General"))
        self.line_site_description.setPlaceholderText(_translate("MainWindow", "Description"))
        self.line_project_descirption.setPlaceholderText(_translate("MainWindow", "Description"))
        self.line_given_name.setPlaceholderText(_translate("MainWindow", "GivenName"))
        self.line_project_long_name.setPlaceholderText(_translate("MainWindow", "LongName"))
        self.line_organization_name.setPlaceholderText(_translate("MainWindow", "Name"))
        self.line_organization_description.setPlaceholderText(_translate("MainWindow", "Description"))
        self.line_project_phase.setPlaceholderText(_translate("MainWindow", "Phase"))
        self.label_11.setText(_translate("MainWindow", "IfcSite"))
        self.label.setText(_translate("MainWindow", "IfcOrganization"))
        self.label_10.setText(_translate("MainWindow", "IfcProject"))
        self.label_9.setText(_translate("MainWindow", "Author"))
        self.line_project_name.setPlaceholderText(_translate("MainWindow", "Name"))
        self.line_site_name.setPlaceholderText(_translate("MainWindow", "Name"))
        self.line_family_name.setPlaceholderText(_translate("MainWindow", "FamilyName"))
        self.button_import_info.setText(_translate("MainWindow", "import Information"))
        self.button_save_info.setText(_translate("MainWindow", "Save Information"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Project Information"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionAdd_Project_Information.setText(_translate("MainWindow", "Add Project Information"))
        self.extras()

    def extras(self):
        self.worker = Worker(ui)
        self.data_dict = self.get_project_data()
        self.worker.updateProgress.connect(self.start_transform)
        self.button_import.clicked.connect(self.get_file_name)
        self.button_save.clicked.connect(self.set_save_name)
        self.button_start.clicked.connect(self.worker.start)
        self.button_import_info.clicked.connect(self.import_info)
        self.button_save_info.clicked.connect(self.save_info)

    def import_info(self):
        file_path = QtWidgets.QFileDialog.getOpenFileName(caption= "InformationsDatei",filter = "Info Xml(*.xml)",selectedFilter="Info Xml (*.xml)")[0]
        self.data_dict = import_ifc_data(file_path,self.data_dict)
        self.set_project_data(self.data_dict)

    def save_info(self):
        ifc_data = self.get_project_data()
        file_path = QtWidgets.QFileDialog.getSaveFileName(caption="InformationsDatei", filter="Info Xml(*.xml)",
                                                          selectedFilter="Info Xml (*.xml)")[0]
        if not file_path.endswith(".xml") and file_path != "":
            file_path += ".xml"
        save_ifc_data(file_path,ifc_data)

    def get_file_name(self):
        file_path = QtWidgets.QFileDialog.getOpenFileName(caption= "IFC Datei",filter = "IFC Datei (*.ifc)",selectedFilter="IFC Datei (*.ifc)")[0]
        file_name,extensinsion = os.path.splitext(file_path)
        if file_name != "":
            self.line_import_path.setText(file_path)
            if self.line_save_path.text()=="":
                self.line_save_path.setText(file_name+".ifc")

    def set_save_name(self):

        file_path = QtWidgets.QFileDialog.getSaveFileName(caption= "IFC Datei",filter = "IFC Datei (*.ifc)",selectedFilter="IFC Datei (*.ifc)")[0]
        if not file_path.endswith(".ifc") and file_path !="":
            file_path+= ".ifc"
        self.line_save_path.setText(file_path)

    def start_transform(self,progress):
        self.progressBar.setValue(progress)

    def set_project_data(self,project_data):
        self.line_organization_name.setText(project_data["org_name"]),
        self.line_organization_description.setText(project_data["org_description"]),
        self.line_family_name.setText(project_data["auth_fam_name"]),
        self.line_given_name.setText(project_data["auth_given_name"]),
        self.line_project_name.setText(project_data["proj_name"]),
        self.line_project_long_name.setText(project_data["proj_long_name"]),
        self.line_project_phase.setText(project_data["proj_phase"]),
        self.line_project_descirption.setPlainText(project_data["proj_description"]),
        self.line_site_name.setText(project_data["site_name"]),
        self.line_site_description.setText(project_data["site_description"]),
        self.line_input_x.setText(project_data["ref_x"]),
        self.line_input_y.setText(project_data["ref_y"]),
        self.line_input_z.setText(project_data["ref_z"]),
        self.line_input_epsg.setText(project_data["epsg_in"]),
        self.line_output_epsg.setText(project_data["epsg_out"]),

    def get_project_data(self):

        data_dict = {
            "org_name" : self.line_organization_name.text(),
            "org_description":self.line_organization_description.text(),
            "auth_fam_name":self.line_family_name.text(),
            "auth_given_name":self.line_given_name.text(),
            "proj_name":self.line_project_name.text(),
            "proj_long_name":self.line_project_long_name.text(),
            "proj_phase":self.line_project_phase.text(),
            "proj_description":self.line_project_descirption.toPlainText(),
            "site_name":self.line_site_name.text(),
            "site_description":self.line_site_description.text(),
            "ref_x":self.line_input_x.text(),
            "ref_y":self.line_input_y.text(),
            "ref_z":self.line_input_z.text(),
            "epsg_in":self.line_input_epsg.text(),
            "epsg_out":self.line_output_epsg.text(),
        }


        return data_dict
class Worker(QtCore.QThread):
    updateProgress = QtCore.Signal(int)

    def __init__(self,ui:Ui_MainWindow):
        QtCore.QThread.__init__(self)
        self.ui  = ui

    def run(self):
        self.ui.data_dict = self.ui.get_project_data()
        path_import = ui.line_import_path.text()
        path_save = ui.line_save_path.text()

        epsg_input = int(ui.line_input_epsg.text())
        epsg_ouptut = int(ui.line_output_epsg.text())

        ref_x = float(ui.line_input_x.text())
        ref_y = float(ui.line_input_y.text())
        ref_z = float(ui.line_input_z.text())

        reference_point = (ref_x, ref_y, ref_z)

        checkstate_referencepoint = ui.check_reference_point.isChecked()
        checkstate_address = ui.check_address.isChecked()

        self.ui.status.setText("Status: Processing")

        generator = Transform_generator(path=path_import,
                    dst=path_save,
                    reference_point_db_ref=reference_point,
                    import_address=checkstate_address,
                    move_reference=checkstate_referencepoint,
                    epsg_in=epsg_input,
                    epsg_out=epsg_ouptut,ifc_data=self.ui.data_dict)

        for building,total in generator:
            self.updateProgress.emit(int(building/total*100))

        self.updateProgress.emit(100)

        self.ui.status.setText("Status: Done!")


if __name__ == "__main__":
    import sys

    doc = "mvdXML_V1.1.xsd"
    file = "Examples/mvdXML_V1-1-Final-Documentation.xml"
    file2 = "Examples/Prüfregeln.mvdxml"
    file3 = "Examples/RelAssociatesMaterial.xml"

    application = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(application.exec())
