# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from CityGML2IFC import Transform_generator
import os
import time

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1341, 334)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line_import_path = QtWidgets.QLineEdit(self.centralwidget)
        self.line_import_path.setObjectName("line_import_path")
        self.gridLayout_3.addWidget(self.line_import_path, 0, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 4, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 5, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.check_reference_point = QtWidgets.QCheckBox(self.frame_2)
        self.check_reference_point.setChecked(True)
        self.check_reference_point.setObjectName("check_reference_point")
        self.verticalLayout.addWidget(self.check_reference_point)
        self.check_address = QtWidgets.QCheckBox(self.frame_2)
        self.check_address.setChecked(True)
        self.check_address.setObjectName("check_address")
        self.verticalLayout.addWidget(self.check_address)
        self.gridLayout_2.addWidget(self.frame_2, 1, 3, 4, 1)
        self.line_input_epsg = QtWidgets.QLineEdit(self.frame)
        self.line_input_epsg.setObjectName("line_input_epsg")
        self.gridLayout_2.addWidget(self.line_input_epsg, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.line_output_epsg = QtWidgets.QLineEdit(self.frame)
        self.line_output_epsg.setObjectName("line_output_epsg")
        self.gridLayout_2.addWidget(self.line_output_epsg, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 2, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.line_input_x = QtWidgets.QLineEdit(self.frame_3)
        self.line_input_x.setObjectName("line_input_x")
        self.gridLayout.addWidget(self.line_input_x, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.line_input_y = QtWidgets.QLineEdit(self.frame_3)
        self.line_input_y.setObjectName("line_input_y")
        self.gridLayout.addWidget(self.line_input_y, 1, 1, 1, 1)
        self.line_input_z = QtWidgets.QLineEdit(self.frame_3)
        self.line_input_z.setObjectName("line_input_z")
        self.gridLayout.addWidget(self.line_input_z, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 4, 1, 1, 2)
        self.gridLayout_3.addWidget(self.frame, 2, 0, 1, 2)
        self.button_import = QtWidgets.QPushButton(self.centralwidget)
        self.button_import.setObjectName("button_import")
        self.gridLayout_3.addWidget(self.button_import, 0, 0, 1, 1)
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setObjectName("button_start")
        self.gridLayout_3.addWidget(self.button_start, 3, 0, 1, 2)
        self.button_save = QtWidgets.QPushButton(self.centralwidget)
        self.button_save.setObjectName("button_save")
        self.gridLayout_3.addWidget(self.button_save, 1, 0, 1, 1)
        self.line_save_path = QtWidgets.QLineEdit(self.centralwidget)
        self.line_save_path.setObjectName("line_save_path")
        self.gridLayout_3.addWidget(self.line_save_path, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1341, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        # self.actionOpen = QtWidgets.QAction(MainWindow)
        # self.actionOpen.setObjectName("actionOpen")
        # self.actionSave = QtWidgets.QAction(MainWindow)
        # self.actionSave.setObjectName("actionSave")
        self.worker = Worker(ui)
        self.worker.updateProgress.connect(self.start_transform)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.click_event()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CityGML2IFC"))
        self.check_reference_point.setText(_translate("MainWindow", "move by Reference Point"))
        self.check_address.setText(_translate("MainWindow", "import Address"))
        self.line_input_epsg.setText(_translate("MainWindow", "25832"))
        self.label_2.setText(_translate("MainWindow", "EPSG Code"))
        self.label.setText(_translate("MainWindow", "Transformation"))
        self.line_output_epsg.setText(_translate("MainWindow", "5683"))
        self.label_7.setText(_translate("MainWindow", "Input Code"))
        self.label_3.setText(_translate("MainWindow", "Reference Point"))
        self.label_8.setText(_translate("MainWindow", "Output Code"))
        self.line_input_x.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Z"))
        self.label_4.setText(_translate("MainWindow", "X"))
        self.line_input_y.setText(_translate("MainWindow", "0"))
        self.line_input_z.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Y"))
        self.button_import.setText(_translate("MainWindow", "Import GML"))
        self.button_start.setText(_translate("MainWindow", "Start"))
        self.button_save.setText(_translate("MainWindow", "Save As"))
        # self.actionOpen.setText(_translate("MainWindow", "Open"))
        # self.actionSave.setText(_translate("MainWindow", "Save"))


    def click_event(self):
        self.button_import.clicked.connect(self.get_file_name)
        self.button_save.clicked.connect(self.set_save_name)
        self.button_start.clicked.connect(self.worker.start)

    def get_file_name(self):
        file_path = QtWidgets.QFileDialog.getOpenFileName()[0]
        file_name,extensinsion = os.path.splitext(file_path)
        if file_name != "":
            self.line_import_path.setText(file_path)
            if self.line_save_path.text()=="":
                self.line_save_path.setText(file_name+".ifc")

    def set_save_name(self):

        file_path = QtWidgets.QFileDialog.getSaveFileName(caption= "IFC Datei",filter = "IFC Datei (*.ifc)",selectedFilter="IFC Datei (*.ifc)")[0]
        if not file_path.endswith(".ifc") and file_path !="":
            file_path+= ".ifc"
        self.line_save_path.setText(file_path)

    def start_transform(self,progress):
        self.progressBar.setValue(progress)


class Worker(QtCore.QThread):
    updateProgress = QtCore.Signal(int)

    def __init__(self,ui):
        QtCore.QThread.__init__(self)

    def run(self):
        path_import = ui.line_import_path.text()
        path_save = ui.line_save_path.text()

        epsg_input = int(ui.line_input_epsg.text())
        epsg_ouptut = int(ui.line_output_epsg.text())

        ref_x = float(ui.line_input_x.text())
        ref_y = float(ui.line_input_y.text())
        ref_z = float(ui.line_input_z.text())

        reference_point = (ref_x, ref_y, ref_z)

        checkstate_referencepoint = ui.check_reference_point.isChecked()
        checkstate_address = ui.check_address.isChecked()

        print(reference_point)
        print(checkstate_referencepoint)
        print(checkstate_address)

        generator = Transform_generator(path=path_import,
                    dst=path_save,
                    reference_point_db_ref=reference_point,
                    import_address=checkstate_address,
                    move_reference=checkstate_referencepoint,
                    epsg_in=epsg_input,
                    epsg_out=epsg_ouptut)

        for building,total in generator:
            self.updateProgress.emit(int(building/total*100))

if __name__ == "__main__":
    import sys

    doc = "mvdXML_V1.1.xsd"
    file = "Examples/mvdXML_V1-1-Final-Documentation.xml"
    file2 = "Examples/Prüfregeln.mvdxml"
    file3 = "Examples/RelAssociatesMaterial.xml"

    application = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(application.exec())
